services:
  php:
    image: clean-structure/symfony:0.2
    restart: unless-stopped
    build:
      context: .
      target: php-dev
      dockerfile: docker/php/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    env_file:
      - path: .env
    volumes:
      - ./:/var/www
    ports:
      - "8085:80"
    logging:
      options:
        max-file: 1
        max-size: 5m
