nelmio_api_doc:
    documentation:
        info:
            title: Clean Structure
            description: Example of using the Clean Structure when creating API by symfony
            version: 1.0.0
    areas:
#        path_patterns:
#            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        default:
          path_patterns: [ ^/api ]
        internal:
          with_attribute: true
